# -*- coding: utf-8 -*-
"""Bhaskara.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfsNhn1uh8g_7gUOU7eMk7GLMYkuCZe_
"""

import math
import matplotlib.pyplot as plt
import numpy as np

comprimento = float(input("Informe o comprimento inicial: "))
largura = float(input("Informe o largura inicial: "))
area_final = float(input("Informe a nova área: "))
a = 1.0
b = largura + comprimento
c = largura * comprimento - area_final
print (f'{a}x²+{b}x+{c}=0')

#calculo do delta

delta = pow(b,2)-4*a*c
print(f'Δ={delta}')
if delta <0:
  print( "A equação não possuirá valores reais")
else:
  if delta == 0:
    print("A equação terá somente um valor real ou dois resultados iguais")
  else:
    x1=(-b+math.sqrt(delta))/2*a
    x2=(-b-math.sqrt(delta))/2*a
    print(f"x'= {x1}")
    print(f'x"= {x2}')
    print(f"Ampliar {x1} metros no comprimento e na largura")

#fazer gráfico

xpoint = np.array([0,0,largura,largura,0]) 
ypoint = np.array([0,comprimento,comprimento,0,0])

xnpoint = np.array([0,0,largura+x1,largura+x1,0])
ynpoint = np.array([0,comprimento+x1,comprimento+x1,0,0])

plt.plot(xpoint, ypoint)
plt.plot(xnpoint, ynpoint)

plt.title("Terreno")
plt.xlabel("Largura")
plt.ylabel("Comprimento")
plt.plot(xpoint,ypoint,color='green')
plt.scatter(xpoint,ypoint,color='red')
plt.scatter(xnpoint,ynpoint,color='blue')
plt.grid()
plt.show()